#!/usr/bin/env bash

wikidir="/usr/share/doc/arch-wiki/html/en/"

wikidocs="$(find ${wikidir} -iname "*.html")"

main() {

    choice=$(printf '%s\n' "${wikidocs[@]}" | \
             cut -d '/' -f8- | \
             sed -e 's/_/ /g' -e 's/.html//g' | \
             sort | \
             rofi -dmenu -i -l 20 -p 'Arch wiki ') || exit 1
    if [ "$choice" ]; then
        path=$(printf '%s\n' "${wikidir}${choice}.html" | sed 's/ /_/g')
        xdg-open "$path"
    else
       echo "Terminated" && exit 0
    fi
}

main
